language: python
sudo: false
env:
  global:
    BUILD_DOCS_BRANCH: master
    DOCS_SUBDIR: doc/
    TARGET_DEV_SUBDIR: databroker/
    HTML_SUBDIR: build/html
    DOCS_CONDA_DEPS: "matplotlib"
    DOCS_PIP_DEPS: "tqdm"

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
    - mongodb-org

matrix:
  include:
    - python: 2.7
      env: BUILD_DOCS=false
    - python: 3.5
      env: BUILD_DOCS=false
    - python: 3.6
      env: BUILD_DOCS=true

before_install:
  - git clone https://github.com/nsls-ii/nsls2-ci ~/ci_scripts
  - . ~/ci_scripts/install-miniconda.sh
  - . ~/ci_scripts/init-filestore.sh
  - . ~/ci_scripts/init-metadatastore.sh

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n testenv pytest cytoolz pandas ujson six jsonschema doct h5py tornado pymongo pytz numpy tifffile jinja2 coverage pyyaml tzlocal nose python=$TRAVIS_PYTHON_VERSION pims prettytable pip boltons requests -c lightsource2-tag -c conda-forge
  - source activate testenv
  - pip install mongoquery attrs tzlocal
  - pip install coveralls codecov pytest-cov
  - |
    if [ $TRAVIS_PYTHON_VERSION = "2.7" ]; then
      pip install singledispatch pathlib2;
    fi;
  - |
    if [ $TRAVIS_PYTHON_VERSION != "2.7" ]; then
      pip install https://github.com/NSLS-II/bluesky/zipball/master#egg=bluesky
    fi;
  - 'pip install https://github.com/NSLS-II/event-model/zipball/master#egg=event_model'
  - pip install -ve .

script:
  - source activate testenv
  # - nohup python /home/travis/metadataservice/startup.py --mongo-host localhost --mongo-port 27017 --service-port 7778 --database mdservicetest --timezone US/Eastern --auth --mongo-user tom --mongo-pwd jerry &
  # - sleep 5
  # - export PYTHONPATH=$PYTHONPATH:/home/travis/metadataclient
  # - cat nohup.out

  - coverage run run_tests.py
  - |
    if [ $BUILD_DOCS == true ]; then
      source ~/ci_scripts/make-docs.sh
    fi

after_success:
  - codecov
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'NSLS-II/databroker' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then
      echo "Adding encrypted deployment key for uploading docs"
      openssl aes-256-cbc -K $encrypted_fc5d6c7ff840_key -iv $encrypted_fc5d6c7ff840_iv -in databroker-docs-deploy.enc -out databroker-docs-deploy -d
      eval `ssh-agent -s`
      chmod 600 databroker-docs-deploy
      ssh-add databroker-docs-deploy
      source ~/ci_scripts/push-docs.sh
    fi
